name: thermal_print
description: Mobile POS terminal with ESC/POS thermal printing, backed by RTS.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
